[project]
name = "quickbake"
version = "0.9.0"
description = "Python environment for testing and linting plugin code"
requires-python = ">=3.12"
dependencies = [
    "coverage>=7.13.2",
    "fake-bpy-module>=20260128",
    "pytest>=9.0.2",
    "pytest-cov>=7.0.0",
    "ruff>=0.14.14",
]

[tool.ruff.lint]
extend-select = ["I"]
ignore = ["F401"]

[tool.ruff.format]
quote-style = "single"

[tool.pytest.ini_options]
pythonpath = ["src"]
addopts = "--cov=src --cov-branch --cov-fail-under=100"

[tool.coverage.run]
branch = false
source = ["src"]

[tool.coverage.paths]
source = ["src"]

[tool.coverage.report]
show_missing = true
fail_under = 100
